### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by 0xdeb** [DanBeckett/door4-customer-prefix-patch#1]
Hey there, thank you for sharing that code. I tried deploying it and it does not di:compile.
Removing Line 8 and not declaring the variable here works just fine. 
PHP Parse error:  syntax error, unexpected 'Options' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in <path>/app/code/Door4/CustomerPrefixPatch/Plugin/Sales/Model/Order/Address/PrefixPatch.php on line 8

**Comment by DanBeckett** [comment]
Ah, thanks. Yeah the type declaration was left in - originally developed this on PHP7.4. Have removed it now so it'll work with older versions of PHP without the issue you had.
