### ISSUE TITLE
array_key_exist missing in PrefixPatch class

### ISSUE THREAD

**Issue by Alainvdz99** [DanBeckett/door4-customer-prefix-patch#3]
Getting an undefined index error because the array_key_exist function is missing in line 34 in the PrefixPatch.php. New if statement should be:
` if (is_array($result) && array_key_exists('prefix', $result) && (!empty($result['prefix']) || $result['prefix'] === "0")) {`

**Comment by DanBeckett** [comment]
Thanks, have committed that change. Where in M2 did you see it behave like that?

**Comment by Alainvdz99** [comment]
@DanBeckett We have a shipping method that will deliver to a post location instead of someone's address. So in that case the customer doenst have to fill in his address info and that means there's also no prefix
